# GENERATED BY KOMAND SDK - DO NOT EDIT
from setuptools import setup, find_packages


setup(name='skadi-komand-plugin',
      version='1.0.0',
      description='Open source collection of tools for digital forensics',
      author='komand',
      author_email='',
      url='',
      packages=find_packages(),
      install_requires=['komand'],  # Add third-party dependencies to requirements.txt, not here!
      scripts=['bin/komand_skadi']
      )
