# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rc_pb2 as rc__pb2


class RCStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExecuteRC = channel.unary_unary(
        '/rc.RC/ExecuteRC',
        request_serializer=rc__pb2.RCRequest.SerializeToString,
        response_deserializer=rc__pb2.RCReply.FromString,
        )


class RCServicer(object):
  """The greeting service definition.
  """

  def ExecuteRC(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RCServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExecuteRC': grpc.unary_unary_rpc_method_handler(
          servicer.ExecuteRC,
          request_deserializer=rc__pb2.RCRequest.FromString,
          response_serializer=rc__pb2.RCReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'rc.RC', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
