# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class DataprocessingMvlocalInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "destination_local": {
      "type": "string",
      "title": "Destination Local",
      "description": "Destination local",
      "order": 2
    },
    "source_local": {
      "type": "string",
      "title": "Source Local",
      "description": "Source local",
      "order": 1
    }
  },
  "required": [
    "source_local",
    "destination_local"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class DataprocessingMvlocalOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "results": {
      "type": "string",
      "title": "Results",
      "description": "Output results",
      "order": 1
    }
  },
  "required": [
    "results"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
