# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "skadivm/skadi_server"
  config.vm.define "skadi_server"
  # Uncomment this line to choose specific version
  # config.vm.box_version = "2018.3"
  config.vm.network "forwarded_port", guest: 80, host: 80
  # These are examples of how to expose more ports and add to VM networks
  # config.vm.network "forwarded_port", guest: 443, host: 8443
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Change the following to align with resources available
  config.vm.provider :virtualbox do |vb|
    vb.name = "skadi_server"
    vb.customize [
      "modifyvm", :id,
      # Minimum / Recommended
      # - CPU: 4 / 8
      # - MEM: 8192 / 16384
      "--cpus", "4",
      "--memory", "8192",
    ]
    # Uncomment this line to bring up the GUI as the VM starts
    # vb.gui = true
  end
  # Uncomment the following lines to run the update script each time the VM is created
  # config.vm.provision "shell", inline: <<-SHELL
  #   /opt/skadi/update.sh
  #   SHELL
end
