# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class ElasticsearchListInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "host": {
      "type": "string",
      "title": "Host",
      "description": "Host to connect to",
      "order": 1
    },
    "store_true": {
      "type": "string",
      "title": "Store True",
      "description": "Command to execute on remote host",
      "order": 2
    }
  },
  "required": [
    "store_true"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ElasticsearchListOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "results": {
      "type": "string",
      "title": "Results",
      "description": "Output results",
      "order": 1
    }
  },
  "required": [
    "results"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
