# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class TimesketchDeleteuserInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "b64_password": {
      "type": "string",
      "title": "B64 Password",
      "description": "b64_password",
      "order": 2
    },
    "timesketch_name": {
      "type": "string",
      "title": "Timesketch Name",
      "description": "timesketch_name",
      "order": 1
    }
  },
  "required": [
    "timesketch_name",
    "b64_password"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class TimesketchDeleteuserOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "results": {
      "type": "string",
      "title": "Results",
      "description": "Output results",
      "order": 1
    }
  },
  "required": [
    "results"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
