# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class ElasticsearchDeleteInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "command": {
      "type": "string",
      "title": "Command",
      "description": "Command to execute on remote host",
      "order": 2
    },
    "index_name": {
      "type": "string",
      "title": "Index Name",
      "description": "ElasticSearch index name to delete",
      "order": 1
    }
  },
  "required": [
    "command"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ElasticsearchDeleteOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "results": {
      "type": "string",
      "title": "Results",
      "description": "Output results",
      "order": 1
    }
  },
  "required": [
    "results"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
