# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "google/gce"
  #config.vm.network "forwarded_port", guest: 80, host: 80

  # Uncomment this line to choose specific version
  # config.vm.box_version = "2018.3"

  # Change the following to align with resources available
  config.vm.provider :google do |google, override|
    google.name = "skadi-server"
    google.google_project_id = "enter GCP project id here"
    google.google_client_email = "enter service account email here"
    google.google_json_key_location = "..\\..\\auth_files\\creds_gcp.json"

    google.instance_ready_timeout = '90'
    google.image_family = 'skadi-server'
    google.disk_size = '20'
    google.disk_type = 'pd-standard'
    google.machine_type = 'n1-standard-4'
    override.ssh.username = "alan"
    override.ssh.private_key_path = "C:\\Users\\asorl\\.ssh\\google_compute_engine"
    #override.ssh.private_key_path = "~/.ssh/id_rsa"
    #override.ssh.private_key_path = "~/.ssh/google_compute_engine"
  end
  # Uncomment the following lines to run the update script each time the VM is created
  # config.vm.provision "shell", inline: <<-SHELL
  #   /opt/skadi/update.sh
  #   SHELL
end
