# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "skadivm/skadi_desktop"
  # Uncomment this line to choose specific version
  # config.vm.box_version = "2018.3"

  # Change the following to align with resources available
  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "modifyvm", :id,
      "--cpus", "6",
      "--memory", "12288",
    ]
    vb.gui = true
    vb.name = "skadi_desktop"
  end
  # Uncomment the following lines to run the update script each time the VM is created
  # config.vm.provision "shell", inline: <<-SHELL
  #   /opt/skadi/update.sh
  #   SHELL
end
