# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class DataprocessingMovefromawsInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "bucket": {
      "type": "string",
      "title": "Bucket",
      "description": "Bucket in AWS",
      "order": 2
    },
    "destination": {
      "type": "string",
      "title": "Destination",
      "description": "Destination",
      "order": 1
    },
    "prefix": {
      "type": "string",
      "title": "Prefix",
      "description": "Prefix",
      "order": 3
    }
  },
  "required": [
    "destination",
    "bucket",
    "prefix"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class DataprocessingMovefromawsOutput(komand.Output):
    schema = json.loads("""
   {}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
