# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "skadivm/skadi_desktop"
  config.vm.define "skadi_desktop"
  # Uncomment this line to choose specific version
  # config.vm.box_version = "2018.3"

  # Change the following to align with resources available
  ["vmware_desktop"].each do |provider|
    config.vm.provider provider do |v, override|
      v.name = "skadi_desktop"
      v.gui = true
      v.vmx["memsize"] = "12288"
      v.vmx["numvcpus"] = "6"
      #v.vmx["cpuid.coresPerSocket"] = "6"
    end
  end
  # Uncomment the following lines to run the update script each time the VM is created
  # config.vm.provision "shell", inline: <<-SHELL
  #   /opt/skadi/update.sh
  #   SHELL
end
